version: "3"

services:
  main:
    container_name: bfair
    image: "jpconsuegra/bfair"
    build: "."
    volumes:
      - "./:/home/coder/bfair"
      - "~/.ssh:/home/coder/.ssh"
      - "~/.gitconfig:/home/coder/.gitconfig"
      - "~/.autogoal:/home/coder/.autogoal"
      - "./vendor/autogoal/:/home/coder/autogoal"
      - "./vendor/autogoal/autogoal:/usr/lib/python3/dist-packages/autogoal"
      - "./vendor/autogoal/vendor/illiterate/illiterate:/usr/lib/python3/dist-packages/illiterate"
    network_mode: "host"
    depends_on:
      - autogoal
    user: "1000:1000"

  autogoal:
    image: "jpconsuegra/autogoal"
    build: "./vendor/autogoal/"
    hostname: autogoal
    volumes: 
      - "~/.autogoal:/home/coder/.autogoal"
    user: "1000:1000"