ADULT_DATASET = "datasets/adult/"
COMPAS_DATASET = "datasets/compas/"
GERMAN_DATASET = "datasets/german/"
IMDB_REVIEWS_DATASET = "datasets/imdb-reviews/"
TOXICITY_DATASET = "datasets/jigsaw-unintended-bias-in-toxicity-classification/"
VICTORIA_DATASET = "datasets/victoria/LLMs/"
ILENIA_DATASET = "datasets/ilenia/"
VILLANOS_DATASET = "datasets/villanos/"

DEBIASED_WORD2VEC_PATH = "embeddings/GoogleNews-vectors-negative300-hard-debiased.bin"
